config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  get '/login',   to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'

  namespace :admin do
    root to: '/admin#index'

    resources :students
    resources :teachers
    resources :courses
    resources :klasses do
      put :enroll,    on: :member
      put :unenroll,  on: :member
    end
  end

  resources :students
  resources :teachers,  only: [:index, :show]
  resources :courses,   only: [:index, :show]
  resources :klasses,   only: [:show] do
    put :enroll,    on: :member
    put :unenroll,  on: :member
  end
  resources :reviews
end

app/models/student.rb
class Student < ApplicationRecord
  include ActiveModel::AttributeAssignment
  attr_accessor :full_name

  has_many :klasses, dependent: :destroy
  has_many :teachers, through: :klasses
  has_many :courses, through: :klasses
  has_many :reviews, through: :klasses
  has_secure_password

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: EMAIL_REGEX
  validates :password, presence: true, :length => { in: 6..20 }

  def full_name
    "#{first_name} #{last_name}"
  end

  # find better solution to move
  # this method to klass.rb instead
  def klasses_for_enrollment
    klass_ids = []
    student_klasses = klasses.pluck(:course_id, :teacher_id)
    student_klasses.each do |sk|
      klass_ids <<
        Klass.offered_klasses.find_by(
          course_id: sk.first,
          teacher_id: sk.last
        ).id
    end

    Klass.offered_klasses.where.not(id: klass_ids)
  end
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def edit
    @student = Student.find(params[:id])
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to admin_student_path(@student),
        notice: 'Student was successfully created.'
    else
      render :new
    end
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to admin_student_path(@student),
        notice: 'Student was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to admin_students_url,
      notice: 'Student was successfully destroyed.'
  end

  private

  def student_params
    params.require(:student).permit(
      :email,
      :first_name,
      :last_name,
      :password,
      :password_confirmation
    )
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      session[:email] = @student.email
      redirect_to login_path,
        notice: 'Student was successfully created.'
    else
      render :new
    end
  end

  def show
    @student = Student.find(params[:id])
  end

  def edit
    @student = Student.find(params[:id])
  end

  private

  def student_params
    params.require(:student).permit(
      :email,
      :first_name,
      :last_name,
      :password,
      :password_confirmation
    )
  end
end

app/views/students/create.html.erb
<h1>Students#create</h1>
<p>Find me in app/views/students/create.html.erb</p>

app/views/students/edit.html.erb
<h1>New Student</h1>

<%= render '/admin/students/form', student: @student, path: students_path %>

<% if current_user %>
  <%= link_to 'Back', student_path(current_user) %>
<% else %>
  <%= link_to 'Back', login_path %>
<% end %>

app/views/students/new.html.erb
<div class='row'>
  <div class='col-md-4 offset-md-4'>
    <h1 class='text-center'>New Student</h1>
    <div class='md-margin-top'>
      <%= render '/admin/students/form', student: @student, path: students_path %>
      <%= link_to 'Back', login_path, class: 'btn btn-dark text-light back-btn float-right' %>
    </div>
  </div>
</div>

app/views/students/show.html.erb
<h1>My Courses</h1>
<h6 class='inline-flex xs-margin-right'>
  <kbd><%= @student.full_name %></kbd>
</h6>

<% if @student.reviews.present? %>
  <div class='row md-margin-top'>
    <div class='col'>
      <h5>Reviews</h5>
      <div id="accordion">
        <% @student.reviews.each_with_index do |review, index| %>
          <div class="card">
            <div class="card-header">
              <%= link_to review.klass.course.name, "#collapse_#{index}",
                class: 'card-link bg-transparent text-secondary',
                'data-toggle': 'collapse' %>
              <span class='small'>by <%= review.klass.teacher.full_name %></span>
            </div>
            <div id=<%= "collapse_#{index}" %> class="collapse" data-parent="#accordion">
              <div class="card-body">
                <span>(Rating: <%= review.rating %>)</span>
                <span><%= review.description %></span>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<div class='row md-margin-top'>
  <div class='col'>
    <h5>Enrolled Courses</h5>
    <ul class='list-group'>
      <% @student.klasses.each do |klass| %>
        <li class='list-group-item'>
          (Rating: <%= klass.klass_rating.nan? ? '–' : klass.klass_rating %>)
          <%= link_to truncate(klass.course.name, length: 50), klass_path(klass),
            class: 'bg-transparent text-secondary' %>
          <span class='small'>
            by <%= link_to klass.teacher.full_name, teacher_path(klass.teacher),
              class: 'bg-transparent text-secondary' %>
          </span>

          <% if current_user && current_user == @student %>
            <%= link_to 'Unenroll',
              unenroll_klass_path(klass),
              method: :put,
              class: 'bg-transparent float-right text-danger' %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<% if current_user == @student %>
  <div class='row md-margin-top'>
    <div class='col'>
      <h5>Available Courses</h5>
      <ul class='list-group'>
        <% @student.klasses_for_enrollment.includes(:teacher).each do |klass| %>
          <li class='list-group-item'>
            (Rating: <%= klass.klass_rating.nan? ? '–' : klass.klass_rating %>)
            <%= link_to truncate(klass.course.name, length: 50), klass_path(klass), class: 'bg-transparent text-secondary' %> by
            <%= link_to klass.teacher.full_name,
              teacher_path(klass.teacher), class: 'bg-transparent text-secondary' %>

            <% if current_user.present? %>
              <%= link_to 'Enroll', enroll_klass_path(klass),
                method: :put,
                class: 'bg-transparent float-right text-success' %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class='md-margin-top inline-flex'>
    <%= link_to 'Settings', edit_student_path(@student), class: 'btn btn-primary text-light' %>
  </div>
<% end %>

<div class='md-margin-top back-btn'>
  <%= link_to 'Back', root_path, class: 'btn btn-dark text-light' %>
</div>