config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  get '/login',   to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'

  namespace :admin do
    root to: '/admin#index'

    resources :students
    resources :teachers
    resources :courses
    resources :klasses do
      put :enroll,    on: :member
      put :unenroll,  on: :member
    end
  end

  resources :students
  resources :teachers,  only: [:index, :show]
  resources :courses,   only: [:index, :show]
  resources :klasses,   only: [:show] do
    put :enroll,    on: :member
    put :unenroll,  on: :member
  end
  resources :reviews
end

app/models/student.rb
class Student < ApplicationRecord
  include ActiveModel::AttributeAssignment
  attr_accessor :full_name

  has_many :klasses, dependent: :destroy
  has_many :teachers, through: :klasses
  has_many :courses, through: :klasses
  has_many :reviews, through: :klasses
  has_secure_password

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: EMAIL_REGEX
  validates :password, presence: true, :length => { in: 6..20 }

  def full_name
    "#{first_name} #{last_name}"
  end

  # find better solution to move
  # this method to klass.rb instead
  def klasses_for_enrollment
    klass_ids = []
    student_klasses = klasses.pluck(:course_id, :teacher_id)
    student_klasses.each do |sk|
      klass_ids <<
        Klass.offered_klasses.find_by(
          course_id: sk.first,
          teacher_id: sk.last
        ).id
    end

    Klass.offered_klasses.where.not(id: klass_ids)
  end
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def edit
    @student = Student.find(params[:id])
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to admin_student_path(@student),
        notice: 'Student was successfully created.'
    else
      render :new
    end
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to admin_student_path(@student),
        notice: 'Student was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to admin_students_url,
      notice: 'Student was successfully destroyed.'
  end

  private

  def student_params
    params.require(:student).permit(
      :email,
      :first_name,
      :last_name,
      :password,
      :password_confirmation
    )
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      session[:email] = @student.email
      redirect_to login_path,
        notice: 'Student was successfully created.'
    else
      render :new
    end
  end

  def show
    @student = Student.find(params[:id])
  end

  def edit
    @student = Student.find(params[:id])
  end

  private

  def student_params
    params.require(:student).permit(
      :email,
      :first_name,
      :last_name,
      :password,
      :password_confirmation
    )
  end
end

app/views/admin/students/_form.html.haml
= form_with(model: student, url: path, local: true) do |f|
  - if student.errors.any?
    .error-explaination
      .alert.alert-danger
        %ul
          - student.errors.full_messages.each do |message|
            %li= "– #{message}"

  .form-group
    = f.label :email
    = f.text_field :email, class: 'form-control'

  .form-group
    = f.label :first_name, 'First Name'
    = f.text_field :first_name, class: 'form-control'

  .form-group
    = f.label :last_name, 'Last Name'
    = f.text_field :last_name, class: 'form-control'

  .form-group
    = f.label :password
    = f.password_field :password, class: 'form-control'

  .form-group
    = f.label :password_confirmation, 'Password Confirmation'
    = f.password_field :password_confirmation, class: 'form-control'

  = f.submit 'Submit', class: 'btn btn-primary float-right'

app/views/admin/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student, path: admin_student_path(@student) %>

<%= link_to 'Show', admin_student_path(@student) %> |
<%= link_to 'Back', admin_students_path %>

app/views/admin/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Manage Students</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.email %></td>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= link_to 'Show', admin_student_path(student) %></td>
        <td><%= link_to 'Edit', edit_admin_student_path(student) %></td>
        <td><%= link_to 'Destroy', admin_student_path(student), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_admin_student_path %>
<%= link_to 'Back', admin_root_path %>

app/views/admin/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student, path: admin_students_path %>

<%= link_to 'Back', admin_students_path %>

app/views/admin/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>First name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>Enrolled Klasses:</strong>
  <ul>
    <% @student.klasses.order_by_course.each do |klass| %>
      <li>
        <%= klass.course.name %> by <%= klass.teacher.full_name %>
        <%= link_to 'Unenroll',
          unenroll_admin_klass_path(klass.id),
          method: :put %>
      </li>
    <% end %>
  </ul>
</p>

<p>
  <strong>Available Klasses:</strong>
  <ul>
    <% @student.klasses_for_enrollment.includes(:teacher).each do |klass| %>
      <li>
        <%= klass.course.name %> by <%= klass.teacher.full_name %>
        <%= link_to 'Enroll',
          enroll_admin_klass_path(klass.id, student_id: @student.id, course_id: klass.course_id),
          method: :put %>
      </li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_admin_student_path(@student) %> |
<%= link_to 'Back', admin_students_path %>