config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  get '/login',   to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'

  namespace :admin do
    root to: '/admin#index'

    resources :students
    resources :teachers
    resources :courses
    resources :klasses do
      put :enroll,    on: :member
      put :unenroll,  on: :member
    end
  end

  resources :students
  resources :teachers,  only: [:index, :show]
  resources :courses,   only: [:index, :show]
  resources :klasses,   only: [:show] do
    put :enroll,    on: :member
    put :unenroll,  on: :member
  end
  resources :reviews
end

app/controllers/admin/klasses_controller.rb
class Admin::KlassesController < ApplicationController
  def index
    @klasses = Klass.search(params[:q])
  end

  def show
    @klass = Klass.find(params[:id])
    @klass_students = Student.find(@klass.klass_students.map(&:student_id))
  end

  def new
    @klass = Klass.new
    @teachers = Teacher.order(:first_name)
    @students = Student.order(:first_name)
    @courses = Course.order(:name)
  end

  def edit
    @klass = Klass.find(params[:id])
    @teachers = Teacher.order(:first_name)
    @students = Student.order(:first_name)
    @courses = Course.order(:name)
  end

  def create
    @klass = Klass.new(klass_params)
    @teachers = Teacher.order(:first_name)
    @courses = Course.order(:name)

    if @klass.save
      redirect_to admin_klasses_path(@klass),
        notice: 'Klass was successfully created.'
    else
      render :new
    end
  end

  def update
    @klass = Klass.find(params[:id])
    @courses = Course.order(:name)
    @teachers = Teacher.order(:first_name)

    if @klass.update(klass_params)
      redirect_to admin_klasses_path(@klass),
        notice: 'Klass was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @klass = Klass.find(params[:id])
    @klass.destroy
    redirect_to admin_klasses_url,
      notice: 'Klass was successfully destroyed.'
  end

  def enroll
    klass = Klass.find(params[:id])
    new_klass = Klass.new(
      teacher_id: klass.teacher_id,
      course_id: params[:course_id],
      student_id: params[:student_id]
    )
    new_klass.save!
    redirect_to request.referrer
  end

  def unenroll
    klass = Klass.find(params[:id])
    klass = Klass.find_by(
      student_id: klass.student_id,
      course_id: klass.course_id
    )
    klass.destroy
    redirect_to request.referrer
  end

  private

  def klass_params
    params.require(:klass).permit(
      :subject,
      :teacher_id,
      :student_id,
      :course_id,
      :q
    )
  end
end

app/controllers/klasses_controller.rb
class KlassesController < ApplicationController
  def show
    @review = Review.new
    @klass = Klass.find(params[:id])
    @klass_students = Student.find(@klass.klass_students.map(&:student_id))
    @klass_reviews = Review.find(@klass.klass_reviews.pluck(:review_id))

    if current_user.present?
      @is_klass_student = @klass_students.find do |s|
        s.id == current_user.id
      end

      @has_klass_review = @klass_reviews.find do |r|
        current_user.reviews.map(&:id).include?(r.id)
      end
    end

    respond_to do |format|
      format.html
      format.json { render json: { klass: @klass, rating: @klass.klass_rating } }
    end
  end

  def enroll
    klass = Klass.find(params[:id])
    Klass.new(
      student_id: current_user.id,
      course_id: klass.course_id,
      teacher_id: klass.teacher_id
    ).save!
    redirect_to request.referrer
  end

  def unenroll
    klass = Klass.find(params[:id])
    Klass.find_by(
      student_id: current_user.id,
      course_id: klass.course_id,
      teacher_id: klass.teacher_id
    ).destroy
    redirect_to request.referrer
  end
end

app/views/admin/klasses/_form.html.haml
= form_with(model: klass, url: path, local: true) do |f|
  - if klass.errors.any?
    #error_explanation
      %h2= "#{pluralize(klass.errors.count, "error")} prohibited this klass from being saved:"
      %ul
        - klass.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :course
    = f.collection_select :course_id, @courses, :id, :name, include_blank: true

  .field
    = f.label :teacher
    = f.collection_select :teacher_id, @teachers, :id, :full_name, include_blank: true

  = f.submit

app/views/admin/klasses/edit.html.erb
<h1>Editing Klass</h1>

<%= render 'form', klass: @klass, path: admin_klass_path(@klass) %>

<%= link_to 'Show', admin_klass_path(@klass) %> |
<%= link_to 'Back', admin_klasses_path %>

app/views/admin/klasses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Manage Klasses</h1>

<%= render '/shared/search_form',
  path: admin_klasses_path,
  type: 'Klass' %>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Teacher</th>
      <th>Students</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @klasses.offered_klasses.each do |klass| %>
      <tr>
        <td><%= klass.course.name if klass.course %></td>
        <td><%= klass.teacher.full_name %></td>
        <td><%= klass.klass_students.count %></td>
        <td><%= link_to 'Show', admin_klass_path(klass) %></td>
        <td><%= link_to 'Edit', edit_admin_klass_path(klass) %></td>
        <td><%= link_to 'Destroy', admin_klass_path(klass), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Klass', new_admin_klass_path %>
<%= link_to 'Back', admin_root_path %>

app/views/admin/klasses/new.html.erb
<h1>New Klass</h1>

<%= render 'form', klass: @klass, path: admin_klasses_path %>

<%= link_to 'Back', admin_klasses_path %>

app/views/admin/klasses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @klass.course.name %>
</p>

<p>
  <strong>By:</strong>
  <%= @klass.teacher.full_name %>
</p>

<p>
  <strong>Students:</strong>
  <ul>
    <% @klass_students.each do |student| %>
      <li>
        <%= student.full_name %>
        <%= link_to 'Unenroll',
          unenroll_admin_klass_path(
            student.klasses.find_by(
              course_id: @klass.course,
              teacher_id: @klass.teacher
            )
          ), method: :put %>
      </li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_admin_klass_path(@klass) %> |
<%= link_to 'Back', admin_klasses_path %>