config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  get '/login',   to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'

  namespace :admin do
    root to: '/admin#index'

    resources :students
    resources :teachers
    resources :courses
    resources :klasses do
      put :enroll,    on: :member
      put :unenroll,  on: :member
    end
  end

  resources :students
  resources :teachers,  only: [:index, :show]
  resources :courses,   only: [:index, :show]
  resources :klasses,   only: [:show] do
    put :enroll,    on: :member
    put :unenroll,  on: :member
  end
  resources :reviews
end

app/controllers/admin/klasses_controller.rb
class Admin::KlassesController < ApplicationController
  def index
    @klasses = Klass.search(params[:q])
  end

  def show
    @klass = Klass.find(params[:id])
    @klass_students = Student.find(@klass.klass_students.map(&:student_id))
  end

  def new
    @klass = Klass.new
    @teachers = Teacher.order(:first_name)
    @students = Student.order(:first_name)
    @courses = Course.order(:name)
  end

  def edit
    @klass = Klass.find(params[:id])
    @teachers = Teacher.order(:first_name)
    @students = Student.order(:first_name)
    @courses = Course.order(:name)
  end

  def create
    @klass = Klass.new(klass_params)
    @teachers = Teacher.order(:first_name)
    @courses = Course.order(:name)

    if @klass.save
      redirect_to admin_klasses_path(@klass),
        notice: 'Klass was successfully created.'
    else
      render :new
    end
  end

  def update
    @klass = Klass.find(params[:id])
    @courses = Course.order(:name)
    @teachers = Teacher.order(:first_name)

    if @klass.update(klass_params)
      redirect_to admin_klasses_path(@klass),
        notice: 'Klass was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @klass = Klass.find(params[:id])
    @klass.destroy
    redirect_to admin_klasses_url,
      notice: 'Klass was successfully destroyed.'
  end

  def enroll
    klass = Klass.find(params[:id])
    new_klass = Klass.new(
      teacher_id: klass.teacher_id,
      course_id: params[:course_id],
      student_id: params[:student_id]
    )
    new_klass.save!
    redirect_to request.referrer
  end

  def unenroll
    klass = Klass.find(params[:id])
    klass = Klass.find_by(
      student_id: klass.student_id,
      course_id: klass.course_id
    )
    klass.destroy
    redirect_to request.referrer
  end

  private

  def klass_params
    params.require(:klass).permit(
      :subject,
      :teacher_id,
      :student_id,
      :course_id,
      :q
    )
  end
end

app/controllers/klasses_controller.rb
class KlassesController < ApplicationController
  def show
    @review = Review.new
    @klass = Klass.find(params[:id])
    @klass_students = Student.find(@klass.klass_students.map(&:student_id))
    @klass_reviews = Review.find(@klass.klass_reviews.pluck(:review_id))

    if current_user.present?
      @is_klass_student = @klass_students.find do |s|
        s.id == current_user.id
      end

      @has_klass_review = @klass_reviews.find do |r|
        current_user.reviews.map(&:id).include?(r.id)
      end
    end

    respond_to do |format|
      format.html
      format.json { render json: { klass: @klass, rating: @klass.klass_rating } }
    end
  end

  def enroll
    klass = Klass.find(params[:id])
    Klass.new(
      student_id: current_user.id,
      course_id: klass.course_id,
      teacher_id: klass.teacher_id
    ).save!
    redirect_to request.referrer
  end

  def unenroll
    klass = Klass.find(params[:id])
    Klass.find_by(
      student_id: current_user.id,
      course_id: klass.course_id,
      teacher_id: klass.teacher_id
    ).destroy
    redirect_to request.referrer
  end
end

app/views/klasses/show.html.erb
<% if current_user.present? && @is_klass_student %>
  <% action_path = unenroll_klass_path(@klass) %>
  <% action_name = 'Unenroll' %>
  <% action_method = :put %>
<% elsif current_user.present? %>
  <% action_path = enroll_klass_path(@klass) %>
  <% action_name = 'Enroll' %>
  <% action_method = :put %>
<% else %>
  <% action_path = login_path(redirect_to: URI.encode(klass_path(@klass))) %>
  <% action_name = 'Enroll' %>
  <% action_method = :get %>
<% end %>

<% if params[:redirect_to] %>
  <% back_path = URI.decode(params[:redirect_to]) %>
<% else %>
  <% back_path = course_path(@klass.course) %>
<% end %>

<% flash.each do |key, message| %> 
  <p id="<%= key %>">
    <%= message %>
  </p>
<% end %>

<h1><%= @klass.course.name %></h1>
<h6 class='inline-flex xs-margin-right'>
  <kbd><%= @klass.teacher.full_name %></kbd>
</h6>
<% if @klass.klass_rating.nan? %>
  – (Reviews: <%= @klass.klass_reviews.count %>)
<% else %>
  <div class='klass-rating inline-flex xs-margin-right'>
    <div class='stars-outer'>
      <div class='stars-inner'>
      </div>
    </div>
  </div>
  <span class='stars-description small'>
    (Rating: <%= @klass.klass_rating %> | Reviews: <%= @klass.klass_reviews.count %>)
  </span>
<% end %>

<div class='row'>
  <div class='md-margin-top col-md-6'>
    <h5>Students</h5>
    <% if @klass_students.present? %>
      <ul class='list-group'>
        <% @klass_students.each do |ks| %>
          <li class='list-group-item'>
            <%= ks.first_name.titleize %> (<%= ks.email%>)
          </li>
        <% end %>
      </ul>
    <% end %>

    <div class='md-margin-top'>
      <%= link_to action_name, action_path, method: action_method, class: 'btn btn-primary text-light' %>
      <%= link_to 'Back', back_path, class: 'btn btn-dark text-light back-btn' %>
    </div>

    <% if @is_klass_student && !@has_klass_review %>
      <div class='row md-margin-top'>
        <div class='col'>
          <h5 class='md-margin-bottom'>Leave Review</h5>
          <%= render '/reviews/form', review: @review, path: reviews_path(klass_id: @klass.id) %>
        </div>
      </div>
    <% end %>
  </div>

  <div class='md-margin-top col-md-6'>
    <h5>Reviews</h5>
    <% if @klass_reviews.present? %>
      <ul class='list-group'>
        <% @klass_reviews.each do |kr| %>
          <li class='list-group-item'>
            <span>(Rating: <%= kr.rating %>)</span>
            <%= kr.description %> – <%= kr.student.full_name %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>